name = "Pedigree"
uuid = "fd4f9bdd-bf75-4419-92eb-a4eb745abf0e"
version = "0.1.1"
authors = ["Austin Putz <putz.austin@gmail.com>",
           "Juan Steibel <jsteibel@iastate.edu>"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.8"
DataFrames = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"


